/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/knowledge-bases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 知识库列表（第一版数量小，不分页） */
        get: operations["listKnowledgeBases"];
        put?: never;
        /** 创建知识库 */
        post: operations["createKnowledgeBase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-bases/{kbId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: components["parameters"]["KbId"];
            };
            cookie?: never;
        };
        /** 知识库详情 */
        get: operations["getKnowledgeBase"];
        put?: never;
        post?: never;
        /**
         * 删除知识库（需显式确认）
         * @description 采用 `?confirm=true` 查询参数显式确认：未携带 confirm=true 返回 400 CONFIRMATION_REQUIRED。
         *     级联影响：知识库下文档、ES 分块与向量、会话与消息全部删除；ES/MinIO 清理异步补偿执行，
         *     响应中的统计为 MySQL 侧即时结果。
         */
        delete: operations["deleteKnowledgeBase"];
        options?: never;
        head?: never;
        /** 重命名 / 修改描述（部分更新，仅提交需变更字段） */
        patch: operations["updateKnowledgeBase"];
        trace?: never;
    };
    "/api/v1/knowledge-bases/{kbId}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: components["parameters"]["KbId"];
            };
            cookie?: never;
        };
        /** 文档列表（状态筛选 + 分页） */
        get: operations["listDocuments"];
        put?: never;
        /**
         * 上传文档（multipart，立即返回任务受理）
         * @description 返回 202 表示已受理并进入异步流水线（解析→清洗→分块→向量化→入库），进度经
         *     GET /documents/{docId}/task 轮询。文件名不参与对象键与服务端路径。
         *     扫描件 PDF 在解析阶段检出并以任务失败形式呈现（failureReason=SCANNED_PDF_NOT_SUPPORTED），
         *     接口本身仍受理，避免同步解析样本拖慢响应。
         *     PDF 解析器可配置（rag.ingestion.pdf-parser）：默认 pdfbox（仅文本层）；配置为 mineru 时
         *     调远端 mineru-api 服务解析复杂版面/扫描件（OCR），服务不可达时任务失败
         *     （failureReason=PARSER_UNAVAILABLE，502），不静默回退。
         *     多版本语义（R3-P3）：KB 内同名同类型且内容不同 → 作为该文档组的新版本并自动激活
         *     （激活切换在上传受理时发生，入库期间旧版本仍可检索）；同内容 → 409（不论版本组）。
         *     删除激活版本时组内自动回落激活最新的 COMPLETED 旧版。
         */
        post: operations["uploadDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{docId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                docId: components["parameters"]["DocId"];
            };
            cookie?: never;
        };
        /** 文档详情（含当前阶段与失败信息） */
        get: operations["getDocument"];
        put?: never;
        post?: never;
        /**
         * 删除文档
         * @description 文档立即从 MySQL 移除并退出检索边界；ES 分块与 MinIO 对象由补偿任务异步清理。
         */
        delete: operations["deleteDocument"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{docId}/parsed-text": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                docId: components["parameters"]["DocId"];
            };
            cookie?: never;
        };
        /** 解析文本预览（清洗后全文） */
        get: operations["getDocumentParsedText"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{docId}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                docId: components["parameters"]["DocId"];
            };
            cookie?: never;
        };
        /** 分块预览（分页；分块正文唯一存于 ES） */
        get: operations["listDocumentChunks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{docId}/task": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                docId: components["parameters"]["DocId"];
            };
            cookie?: never;
        };
        /**
         * 当前入库任务（状态/阶段/失败原因/尝试次数）
         * @description 任务详情以此端点为准（上传 202 响应已含 task 句柄，文档列表行轮询此端点）；
         *     DocumentDetail 内嵌 task 摘要仅为详情页便利，不承载额外字段。
         */
        get: operations["getDocumentTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{docId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                docId: components["parameters"]["DocId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重试失败的入库任务（复用已完成阶段） */
        post: operations["retryDocumentIngestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{docId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                docId: components["parameters"]["DocId"];
            };
            cookie?: never;
        };
        /**
         * 版本组列表（版本号升序）（R3-P3）
         * @description 返回 docId 所属版本组的全部版本。同名不同内容再上传形成新版本并自动激活；
         *     同内容再上传始终 409 DUPLICATE_DOCUMENT（不论版本组）。
         */
        get: operations["listDocumentVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{docId}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                docId: components["parameters"]["DocId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 激活指定版本（组内其它版本自动失活）（R3-P3）
         * @description 检索只命中激活版本。仅 COMPLETED/FAILED 版本可激活（QUEUED/PROCESSING 中间态
         *     拒绝，400 INVALID_ARGUMENT）；FAILED 版本激活用于从失败的新版本回退旧版语义。
         */
        post: operations["activateDocumentVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 会话列表（可按知识库过滤） */
        get: operations["listSessions"];
        put?: never;
        /** 新建会话 */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        /** 会话详情 */
        get: operations["getSession"];
        put?: never;
        post?: never;
        /** 删除会话（级联删除消息） */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{sessionId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        /** 会话消息（按时间正序，分页） */
        get: operations["listMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qa/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 知识问答（SSE 流式）
         * @description 返回 text/event-stream。传输格式：每个事件为一行 `event: <类型>` + `data: <JSON 载荷>`，
         *     事件间以空行分隔；服务端每 15 秒发送注释行 `:ping` 心跳。
         *
         *     事件类型与载荷（详见 QAStreamEvent oneOf）：
         *     - `stage`    {stage, detail?, elapsedMs?} —— 仅报真实发生的阶段，禁止虚假进度
         *     - `token`    {delta} —— 回答文本增量
         *     - `citations`{citations[]} —— 恰好一次，内容为本次实际检索命中（资料不足时为空数组）；
         *                    恒在 done 之前
         *     - `done`     {messageId, elapsedMs} —— 终态
         *     - `error`    {error{code,message,requestId}} —— 终态；code ∈ MODEL_TIMEOUT /
         *                    MODEL_UNAVAILABLE / RETRIEVAL_FAILED / STREAM_INTERRUPTED / INTERNAL_ERROR
         *     - `canceled` {reason:"USER_CANCELED"} —— 终态；由 POST /qa/cancel 或客户端断连触发
         *
         *     会话历史仅用于对话连贯性，不作为证据；引用只来自本次检索结果。
         *     用户消息在流开始前即持久化，异常后可凭输入重试（QA-8）。
         */
        post: operations["qaStream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qa/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 取消进行中的问答流
         * @description 客户端也可直接断开 SSE 连接取消（服务端检测断连并停止生成）；此端点用于无法可靠
         *     传递断连信号的客户端。对已结束/未知的 clientRequestId 返回 404 CANCEL_TARGET_NOT_FOUND。
         */
        post: operations["qaCancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/debug/retrieval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 检索调试（与问答共用同一检索代码路径与默认配置）
         * @description 返回命中文档与分块、排名与分数、各阶段耗时、实际送入模型的上下文与问题线索
         *     （未召回/全部低于阈值/上下文截断）。供调试页使用；不写入任何会话或消息。
         */
        post: operations["debugRetrieval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eval/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 数据集列表 */
        get: operations["listEvalDatasets"];
        put?: never;
        /**
         * 导入评测数据集（JSON 或 CSV 文件，产生新版本）
         * @description multipart 上传：按文件扩展名/内容识别 .json 或 .csv。每次导入在该数据集下产生一个
         *     不可变版本（versionNo 递增）。字段：question（必填）、referenceAnswer、evidence
         *     （相关文档/证据引用数组）、answerable（是否可回答）、category
         *     （DIRECT/TERM_VARIATION/FOLLOW_UP/OUT_OF_KB/CONFUSABLE）。JSON 文件为对象数组；
         *     CSV 表头须与字段同名（evidence 列为 JSON 字符串）。
         */
        post: operations["importEvalDataset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eval/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 评测运行列表 */
        get: operations["listEvalRuns"];
        put?: never;
        /**
         * 发起评测运行（异步）
         * @description 指定 datasetVersion（缺省取该数据集最新版本）与知识库；检索参数（topK/minScore）缺省取
         *     服务端当前默认值。模型名、embedding 名与维度、检索参数、分块策略快照随运行保存
         *     （configSnapshot），保证两次运行可对比。
         */
        post: operations["createEvalRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eval/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        /** 评测运行详情（指标快照 + 样本结果分页） */
        get: operations["getEvalRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eval/runs/{runId}/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 人工标记样本失败原因 */
        patch: operations["reviewEvalRunItem"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /**
             * @description 稳定错误码枚举（第一版全集）：
             *     INVALID_ARGUMENT, CONFIRMATION_REQUIRED,
             *     KB_NOT_FOUND, KB_NAME_DUPLICATED, DOCUMENT_NOT_FOUND, SESSION_NOT_FOUND,
             *     DUPLICATE_DOCUMENT, UNSUPPORTED_FILE_TYPE, SCANNED_PDF_NOT_SUPPORTED,
             *     FILE_TOO_LARGE, PARSED_TEXT_NOT_READY, TASK_NOT_RETRYABLE,
             *     DUPLICATE_EVAL_DATASET, EVAL_DATASET_NOT_FOUND, EVAL_RUN_NOT_FOUND,
             *     INVALID_DATASET_FILE,
             *     MODEL_TIMEOUT, MODEL_UNAVAILABLE, RETRIEVAL_FAILED, PARSER_UNAVAILABLE,
             *     STREAM_ALREADY_ACTIVE, CANCEL_TARGET_NOT_FOUND, STREAM_INTERRUPTED,
             *     SERVICE_UNAVAILABLE, INTERNAL_ERROR
             * @enum {string}
             */
            code: "INVALID_ARGUMENT" | "CONFIRMATION_REQUIRED" | "KB_NOT_FOUND" | "KB_NAME_DUPLICATED" | "DOCUMENT_NOT_FOUND" | "SESSION_NOT_FOUND" | "DUPLICATE_DOCUMENT" | "UNSUPPORTED_FILE_TYPE" | "SCANNED_PDF_NOT_SUPPORTED" | "FILE_TOO_LARGE" | "PARSED_TEXT_NOT_READY" | "TASK_NOT_RETRYABLE" | "DUPLICATE_EVAL_DATASET" | "EVAL_DATASET_NOT_FOUND" | "EVAL_RUN_NOT_FOUND" | "INVALID_DATASET_FILE" | "MODEL_TIMEOUT" | "MODEL_UNAVAILABLE" | "RETRIEVAL_FAILED" | "PARSER_UNAVAILABLE" | "STREAM_ALREADY_ACTIVE" | "CANCEL_TARGET_NOT_FOUND" | "STREAM_INTERRUPTED" | "SERVICE_UNAVAILABLE" | "INTERNAL_ERROR";
            /** @description 面向用户的人读文案（中文） */
            message: string;
            /** @description 服务端请求标识，同时经 X-Request-Id 响应头返回 */
            requestId: string;
            /** @description 字段级问题或附加信息（如 DUPLICATE_DOCUMENT 的 existingDocumentId） */
            details?: {
                field?: string;
                issue: string;
            }[];
        };
        KnowledgeBase: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string;
            documentCount: number;
            chunkCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        KnowledgeBaseCreate: {
            name: string;
            description?: string;
        };
        KnowledgeBaseUpdate: {
            name?: string;
            description?: string;
        };
        DeletionSummary: {
            /** Format: uuid */
            kbId: string;
            documentsDeleted: number;
            /** @description ES 侧最近已知分块数；实际清理由补偿任务完成，此值不含进行中变更 */
            chunksDeleted?: number;
            sessionsDeleted: number;
            messagesDeleted: number;
            /** @description 已写入清理补偿表的任务数（ES + MinIO） */
            cleanupTasksAccepted: number;
        };
        /** @enum {string} */
        DocumentStatus: "QUEUED" | "PROCESSING" | "COMPLETED" | "FAILED";
        /**
         * @description 真实流水线阶段；SSE 与任务进度均不得出现此枚举之外的“虚假进度”
         * @enum {string}
         */
        PipelineStage: "QUEUED" | "PARSING" | "CLEANING" | "CHUNKING" | "EMBEDDING" | "INDEXING" | "COMPLETED";
        /**
         * @description LENGTH_OVERLAP：按长度+重叠切分；STRUCTURE：按标题/段落结构切分并以 maxLength 封顶。
         *     两者均保留标题路径与可获得页码（KB-6/KB-7）。
         * @enum {string}
         */
        ChunkStrategy: "LENGTH_OVERLAP" | "STRUCTURE";
        ChunkingConfig: {
            strategy: components["schemas"]["ChunkStrategy"];
            maxLength: number;
            overlap: number;
        };
        Document: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            kbId: string;
            name: string;
            /** @enum {string} */
            fileType: "PDF" | "MD" | "TXT" | "DOCX" | "XLSX" | "CSV";
            /** Format: int64 */
            sizeBytes: number;
            status: components["schemas"]["DocumentStatus"];
            currentStage: components["schemas"]["PipelineStage"];
            chunkCount: number;
            /**
             * Format: uuid
             * @description 同源文档组标识 = 组内第一版 document.id（R3-P3）；单版本文档 rootId=id
             */
            rootId: string;
            /** @description 组内版本号，从 1 递增（同名不同内容再上传产生新版本） */
            versionNo: number;
            /** @description 组内激活版本（检索只命中激活版本）；组内至多一个 TRUE */
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        DocumentDetail: components["schemas"]["Document"] & {
            chunkConfig: components["schemas"]["ChunkingConfig"];
            contentSha256: string;
            failureStage?: components["schemas"]["PipelineStage"];
            /** @description 失败错误码 + 人读文案（status=FAILED 时非空） */
            failureReason?: string;
            task?: components["schemas"]["IngestionTask"];
        };
        IngestionTask: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            documentId: string;
            /** @enum {string} */
            status: "QUEUED" | "RUNNING" | "COMPLETED" | "FAILED";
            stage: components["schemas"]["PipelineStage"];
            attempt: number;
            failureStage?: components["schemas"]["PipelineStage"];
            failureReason?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            finishedAt?: string;
        };
        UploadAccepted: {
            document: components["schemas"]["Document"];
            task: components["schemas"]["IngestionTask"];
        };
        ParsedText: {
            /** Format: uuid */
            docId: string;
            /** @description 解析+清洗后文本；受 maxChars 截断时以 truncated 标记 */
            content: string;
            charCount: number;
            truncated?: boolean;
        };
        Chunk: {
            /** @description 确定性 chunkId（docId + "-c" + seq），重试重建不变 */
            id: string;
            /** Format: uuid */
            docId: string;
            seq: number;
            /** @description 标题路径（如 “部署指南 > 常见故障 > 磁盘告警”），无结构时为文档名 */
            titlePath: string;
            /** @description 起始页码；仅 PDF 可获得，MD/TXT 为 null */
            page?: number | null;
            charCount: number;
            text: string;
        };
        DocumentPage: {
            items: components["schemas"]["Document"][];
            page: number;
            pageSize: number;
            total: number;
        };
        ChunkPage: {
            items: components["schemas"]["Chunk"][];
            page: number;
            pageSize: number;
            total: number;
        };
        DocumentDeletionResult: {
            /** Format: uuid */
            docId: string;
            /** @description ES 侧最近已知分块数 */
            chunksDeleted?: number;
            cleanupTasksAccepted: number;
        };
        Session: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            kbId: string;
            title: string;
            messageCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SessionCreate: {
            /** Format: uuid */
            kbId: string;
            /** @description 缺省取首条提问前 N 字 */
            title?: string;
        };
        Citation: {
            chunkId: string;
            /** Format: uuid */
            docId: string;
            docName: string;
            titlePath: string;
            page?: number | null;
            /**
             * Format: float
             * @description 该引用的最终排序分。R2 语义变更：不再是固定 cosine——
             *     VECTOR 模式为余弦相似度，HYBRID 为归一化融合分，HYBRID_RERANK 为重排相关度
             *     （请求内相对值）。字段类型与位置不变，但跨模式的数值不可直接比较；
             *     V1 版本落库的历史引用仍是 cosine 语义（旧数据不作迁移）。
             */
            score: number;
        };
        Message: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            sessionId: string;
            /** @enum {string} */
            role: "USER" | "ASSISTANT";
            content: string;
            /** @description 仅来自该回答对应的实际检索结果；资料不足时为空数组 */
            citations: components["schemas"]["Citation"][];
            /** @enum {string} */
            status: "COMPLETED" | "ERROR" | "CANCELED";
            error?: components["schemas"]["Error"];
            /** Format: date-time */
            createdAt: string;
        };
        MessagePage: {
            items: components["schemas"]["Message"][];
            page: number;
            pageSize: number;
            total: number;
        };
        QAStreamRequest: {
            /**
             * Format: uuid
             * @description 检索严格限定该知识库（QA-1）
             */
            kbId: string;
            /** Format: uuid */
            sessionId: string;
            question: string;
            /**
             * Format: uuid
             * @description 客户端生成的幂等键；重复提交同键请求返回 409 STREAM_ALREADY_ACTIVE
             */
            clientRequestId?: string;
        };
        /**
         * @description SSE 载荷 oneOf。每个 SSE 事件的 data 字段是下列之一，由 event 行标明类型；
         *     顺序约束：citations 恒在 done 之前；done/error/canceled 互斥且为终态。
         */
        QAStreamEvent: components["schemas"]["StreamEventStage"] | components["schemas"]["StreamEventToken"] | components["schemas"]["StreamEventCitations"] | components["schemas"]["StreamEventDone"] | components["schemas"]["StreamEventError"] | components["schemas"]["StreamEventCanceled"];
        StreamEventStage: {
            /**
             * @description 仅报真实发生的阶段（QA-4）
             * @enum {string}
             */
            stage: "RETRIEVAL_STARTED" | "RETRIEVAL_COMPLETED" | "GENERATION_STARTED";
            /** @description 如 “命中 6 块 · 128ms” */
            detail?: string;
            elapsedMs?: number;
        };
        StreamEventToken: {
            /** @description 回答文本增量 */
            delta: string;
        };
        StreamEventCitations: {
            citations: components["schemas"]["Citation"][];
        };
        StreamEventDone: {
            /** Format: uuid */
            messageId: string;
            elapsedMs?: number;
        };
        StreamEventError: {
            error: components["schemas"]["Error"];
        };
        StreamEventCanceled: {
            /** @enum {string} */
            reason: "USER_CANCELED";
        };
        QACancelRequest: {
            /** Format: uuid */
            clientRequestId: string;
        };
        QACancelResult: {
            /** Format: uuid */
            clientRequestId: string;
            /** @constant */
            canceled: true;
        };
        DebugRetrievalRequest: {
            /** Format: uuid */
            kbId: string;
            question: string;
            /** @description 缺省取服务端配置 */
            topK?: number;
            /** @description 缺省取服务端配置 */
            minScore?: number;
            /**
             * @description 检索模式覆盖（R2-D1）；缺省取服务端配置。用于对比「仅向量 / 融合 / 融合+重排」的排序差异
             * @enum {string|null}
             */
            mode?: "VECTOR" | "HYBRID" | "HYBRID_RERANK" | null;
        };
        /**
         * @description 检索模式（R2-H）。VECTOR=仅向量 kNN（第一轮基线）；HYBRID=BM25 与向量双通道候选 + 应用侧 RRF 融合；
         *     HYBRID_RERANK=融合后再调用重排模型定序。
         *     score 语义随模式不同：VECTOR 为余弦相似度；HYBRID 为归一化融合分；
         *     HYBRID_RERANK 为重排相关度（请求内相对值）。三者不可直接比较，切换模式需重新校准 minScore 与拒答阈值。
         * @enum {string}
         */
        RetrievalMode: "VECTOR" | "HYBRID" | "HYBRID_RERANK";
        RetrievalStageRank: {
            /** @enum {string} */
            stage: "vector" | "bm25" | "fused" | "rerank";
            /** @description 该候选在此阶段的位次 */
            rank: number;
            /**
             * Format: float
             * @description 该阶段的原始分数（量纲随阶段不同）
             */
            score: number;
        };
        RetrievalHit: {
            rank: number;
            chunk: components["schemas"]["Chunk"];
            /**
             * Format: float
             * @description 最终排序分（决定 rank 与 passedThreshold）；语义随检索模式不同，见 RetrievalMode
             */
            score: number;
            /** @description 是否通过 minScore 进入上下文 */
            passedThreshold: boolean;
            /**
             * @description 该候选在各检索阶段的位次与分数（R2-D1）。只含实际参与且该候选出现的阶段——
             *     某阶段缺失即表示该通道未召回此候选（此信息本身用于解释排序变化）。
             */
            stages?: components["schemas"]["RetrievalStageRank"][];
            /** @description 排序变化原因（如「RRF 融合调整：向量 */
            rankChangedReason?: string | null;
        };
        DebugTimings: {
            embedMs: number;
            searchMs: number;
            totalMs: number;
        };
        DebugIssue: {
            /**
             * @description RERANK_DEGRADED 表示本次重排未生效、结果使用融合顺序（降级结果不可与正常重排结果直接比较）
             * @enum {string}
             */
            type: "NO_HITS" | "ALL_BELOW_THRESHOLD" | "CONTEXT_TRUNCATED" | "RERANK_DEGRADED";
            message: string;
        };
        DebugRetrievalResult: {
            effectiveConfig: {
                topK: number;
                minScore: number;
                embeddingModel: string;
                dimensions: number;
                /** @description 问答页将使用的生成模型（只读展示） */
                chatModel?: string;
                mode?: components["schemas"]["RetrievalMode"];
                /** @description 各通道候选数上限 */
                candidateLimit?: number;
                /** @description RRF 常数 k */
                rrfK?: number;
                /** @description 重排模型名；未启用重排时为空串 */
                rerankModel?: string;
                /** @description 本次是否会调用重排 */
                rerankEnabled?: boolean;
                /** @description 本次是否发生重排降级（重排未生效） */
                rerankDegraded?: boolean;
                /** @description 降级原因 */
                rerankDegradeReason?: string | null;
            };
            hits: components["schemas"]["RetrievalHit"][];
            timings: components["schemas"]["DebugTimings"];
            context: {
                /** @description 实际送入模型的上下文全文 */
                text: string;
                charCount: number;
                chunkIds: string[];
            };
            issues: components["schemas"]["DebugIssue"][];
        };
        /**
         * @description 调优集与独立测试集严格分离（EV-6）
         * @enum {string}
         */
        DatasetType: "TUNING" | "TEST";
        /** @enum {string} */
        EvalCategory: "DIRECT" | "TERM_VARIATION" | "FOLLOW_UP" | "OUT_OF_KB" | "CONFUSABLE";
        EvidenceRef: {
            docName?: string;
            titlePath?: string;
            page?: number | null;
            snippet?: string;
            /** @description 分块级锚点（v2 数据集起）：分块确定性 id */
            chunkId?: string;
            /**
             * @description 分块级稳定锚点（R3-P1）：分块正文规范化（去首尾空白 + 内部空白折叠为
             *     单空格）后 SHA-256 前 16 hex，由服务端 EvidenceMatcher.contentHashOf
             *     统一计算。与文件名/分块策略解耦——文档改名或重入库导致 chunkId
             *     变化后仍可判定命中。判定时与 chunkId/titlePath/anchorPath 同为
             *     精确相等匹配，优先级最高。
             */
            contentHash?: string;
        };
        EvalDataset: {
            /** Format: uuid */
            id: string;
            name: string;
            datasetType: components["schemas"]["DatasetType"];
            latestVersion: {
                /** Format: uuid */
                versionId: string;
                versionNo: number;
                itemCount: number;
                /** Format: date-time */
                createdAt: string;
            };
            /** Format: date-time */
            createdAt: string;
        };
        EvalRunCreate: {
            /** Format: uuid */
            datasetId: string;
            /**
             * Format: uuid
             * @description 缺省取该数据集最新版本
             */
            versionId?: string;
            /** Format: uuid */
            kbId: string;
            topK?: number;
            minScore?: number;
        };
        EvalRunAccepted: {
            /** Format: uuid */
            runId: string;
            status: components["schemas"]["EvalRunStatus"];
        };
        /** @enum {string} */
        EvalRunStatus: "RUNNING" | "COMPLETED" | "FAILED";
        EvalRunSummary: {
            /** Format: uuid */
            runId: string;
            /** Format: uuid */
            datasetId: string;
            /** Format: uuid */
            datasetVersionId: string;
            /** Format: uuid */
            kbId: string;
            status: components["schemas"]["EvalRunStatus"];
            itemCount: number;
            hitAt1?: number | null;
            hitAt3?: number | null;
            hitAt5?: number | null;
            /** @description R2-E2 Recall@5 = 命中的参考证据分块数 / 参考证据分块总数（分块级口径） */
            recallAt5?: number | null;
            /** @description R2-E2 MRR = 每题首个命中证据分块排名倒数的平均值（未召回计 0） */
            mrr?: number | null;
            /**
             * @description R2-E3 拒答正确率 = (answerable=false 且拒答 + answerable=true 且未拒答) / 已执行题数。
             *     与 Hit@K 分列：资料外题的"是否安全拒答"不再因退出 Hit@K 分母而消失。
             */
            refusalAccuracy?: number | null;
            /** @description R2-E2 正确答案排名分布；键为 "1".."5" 与 "notFound" */
            rankDistribution?: {
                [key: string]: number;
            } | null;
            /** @description R2-L1 平均检索耗时 */
            retrievalMsAvg?: number | null;
            /** @description R2-L1 平均生成耗时 */
            generationMsAvg?: number | null;
            /** @description R2-L1 单题耗时中位数 */
            latencyP50Ms?: number | null;
            /** @description R2-L1 单题耗时 95 分位 */
            latencyP95Ms?: number | null;
            /** @description R2-L1 最慢单题耗时 */
            latencyMaxMs?: number | null;
            /** @description 计入 Hit@K 分母的可答题数 */
            answerableCount?: number | null;
            /** @description 资料外题数（不计入 Hit@K 分母） */
            outOfKbCount?: number | null;
            /** @description 原始 metrics 对象（含上列全部 R2 指标）；未完成运行为 null */
            metrics?: {
                [key: string]: unknown;
            } | null;
            /** @description 运行配置快照；列表页展示检索模式、对比页做可比性守卫（R2-C3） */
            configSnapshot?: {
                [key: string]: unknown;
            } | null;
            /** @description 失败原因（列表行内展示） */
            failureReason?: string | null;
            avgLatencyMs?: number | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            finishedAt?: string | null;
        };
        EvalRunPage: {
            items: components["schemas"]["EvalRunSummary"][];
            page: number;
            pageSize: number;
            total: number;
        };
        EvalHit: {
            rank: number;
            chunkId: string;
            docName: string;
            titlePath: string;
            /** @description 命中分块正文的规范化 SHA-256 前 16 hex（R3-P1，EvidenceMatcher.contentHashOf 计算） */
            contentHash?: string | null;
            page?: number | null;
            /**
             * Format: float
             * @description 最终排序分（语义随检索模式不同，见 RetrievalMode）
             */
            score: number;
            /** @description 是否通过 minScore；未过阈值的命中保留在快照中供调试与归因 */
            passedThreshold?: boolean;
            /** @description 向量通道位次；未参与或未召回为 null */
            vectorRank?: number | null;
            /** @description 向量余弦相似度 */
            vectorScore?: number | null;
            /** @description BM25 通道位次；VECTOR 模式恒为 null */
            bm25Rank?: number | null;
            /** @description BM25 原始分（无上界，不可跨查询比较） */
            bm25Score?: number | null;
            /** @description RRF 融合后位次 */
            fusedRank?: number | null;
            /** @description 归一化融合分（原始 RRF 分保留在调试接口中） */
            fusedScore?: number | null;
            /** @description 重排后位次；未启用或降级为 null */
            rerankRank?: number | null;
            /** @description 重排相关度（请求内相对值，不可跨请求比较） */
            rerankScore?: number | null;
        };
        EvalRunItem: {
            /** Format: uuid */
            id: string;
            seq: number;
            question: string;
            referenceAnswer?: string | null;
            answerable?: boolean;
            category?: components["schemas"]["EvalCategory"];
            /** @description 本次运行的检索命中（快照） */
            retrieved: components["schemas"]["EvalHit"][];
            generatedAnswer?: string | null;
            citations?: components["schemas"]["Citation"][];
            /**
             * @description 参考证据是否出现在命中集中（样本级 Hit@K，K=该次运行 topK）。
             *     R2-E1：判定已下沉到分块级——按 evidence.chunkId / titlePath / anchorPath 与命中分块精确匹配；
             *     不再回退到 docName 相等（那会让指标退化为文档级而失去区分度）。
             */
            hit?: boolean | null;
            latencyMs?: number | null;
            /**
             * @description 正确答案分块在本次 retrieved 中的首个命中位次（1 起，R2-E2）；
             *     未命中或该题为资料外（无参考证据）为 null。
             *     与指标分子同一判定口径（EvidenceMatcher），保证展示与统计一致。
             */
            evidenceRank?: number | null;
            /** @description 该题检索耗时（R2-L1）；旧数据为 null */
            retrievalMs?: number | null;
            /** @description 该题生成耗时（R2-L1）；拒答路径未调用模型，约为 0 */
            generationMs?: number | null;
            /**
             * @description 人工标记的失败原因；未标注为 null
             * @enum {string|null}
             */
            reviewTag?: "OK" | "WRONG_ANSWER" | "MISSING_EVIDENCE" | "WRONG_SOURCE" | "OTHER" | null;
            reviewNote?: string | null;
        };
        EvalRunItemPage: {
            items: components["schemas"]["EvalRunItem"][];
            page: number;
            pageSize: number;
            total: number;
        };
        EvalRunDetail: components["schemas"]["EvalRunSummary"] & {
            /**
             * @description 运行配置快照（EV-4）：chatModel、embeddingModel、embeddingDimensions、
             *     topK、minScore、chunkStrategy、maxChunkChars 等，按实际执行值记录。
             *     R2 增补：retrievalMode、rrfK、candidateLimit、rerankEnabled、rerankModel、
             *     rerankDegradeOnFailure、refusalEnabled、refusalInsufficientThreshold——
             *     缺任一项都会让"改了检索配置"的两次运行无法区分（EV-4）。
             */
            configSnapshot?: {
                [key: string]: unknown;
            };
            failureReason?: string | null;
            items: components["schemas"]["EvalRunItemPage"];
        };
        EvalReviewUpdate: {
            /** @enum {string} */
            reviewTag: "OK" | "WRONG_ANSWER" | "MISSING_EVIDENCE" | "WRONG_SOURCE" | "OTHER";
            reviewNote?: string;
        };
    };
    responses: {
        /** @description 参数非法（INVALID_ARGUMENT；字段级问题在 details 中） */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 资源不存在（KB_NOT_FOUND / DOCUMENT_NOT_FOUND / SESSION_NOT_FOUND） */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 服务内部错误（INTERNAL_ERROR）或依赖不可用（SERVICE_UNAVAILABLE） */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        KbId: string;
        DocId: string;
        SessionId: string;
        RunId: string;
        ItemId: string;
        Page: number;
        PageSize: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listKnowledgeBases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBase"][];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    createKnowledgeBase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeBaseCreate"];
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBase"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description 名称重复（KB_NAME_DUPLICATED） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    getKnowledgeBase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: components["parameters"]["KbId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBase"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    deleteKnowledgeBase: {
        parameters: {
            query: {
                /** @description 必须显式传 true 才执行删除 */
                confirm: true;
            };
            header?: never;
            path: {
                kbId: components["parameters"]["KbId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除已受理，返回影响范围 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletionSummary"];
                };
            };
            /** @description 未确认（CONFIRMATION_REQUIRED） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    updateKnowledgeBase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: components["parameters"]["KbId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeBaseUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBase"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description 名称重复（KB_NAME_DUPLICATED） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    listDocuments: {
        parameters: {
            query?: {
                status?: components["schemas"]["DocumentStatus"];
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                kbId: components["parameters"]["KbId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentPage"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    uploadDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: components["parameters"]["KbId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description 支持 .pdf / .md / .txt / .docx / .xlsx / .csv（R3-P1 扩展 docx/xlsx/csv）；≤50MB。docx/xlsx 须为 OOXML ZIP 容器 （旧版 .doc/.xls 二进制格式不支持）；csv 须为 UTF-8 文本。
                     */
                    file: string;
                    chunkStrategy?: components["schemas"]["ChunkStrategy"];
                    /**
                     * @description 单块最大字符数（两种策略都生效）
                     * @default 800
                     */
                    maxLength?: number;
                    /**
                     * @description 相邻块重叠字符数
                     * @default 100
                     */
                    overlap?: number;
                };
            };
        };
        responses: {
            /** @description 已受理 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadAccepted"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /**
             * @description DUPLICATE_DOCUMENT：同知识库内已存在相同内容哈希的文档；
             *     details 中返回 existingDocumentId。
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description FILE_TOO_LARGE */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description UNSUPPORTED_FILE_TYPE（扩展名/魔数不在白名单） */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    getDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                docId: components["parameters"]["DocId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    deleteDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                docId: components["parameters"]["DocId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除已受理 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDeletionResult"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    getDocumentParsedText: {
        parameters: {
            query?: {
                /** @description 截断返回前 N 字符；缺省返回全文 */
                maxChars?: number;
            };
            header?: never;
            path: {
                docId: components["parameters"]["DocId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParsedText"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description PARSED_TEXT_NOT_READY（解析阶段未完成） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    listDocumentChunks: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                docId: components["parameters"]["DocId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK（尚未分块完成时返回空页，不报错） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkPage"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    getDocumentTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                docId: components["parameters"]["DocId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionTask"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    retryDocumentIngestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                docId: components["parameters"]["DocId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已重新入队 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionTask"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description TASK_NOT_RETRYABLE（任务处于 QUEUED/RUNNING/COMPLETED，不可重试） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    listDocumentVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                docId: components["parameters"]["DocId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 版本列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"][];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    activateDocumentVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                docId: components["parameters"]["DocId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 激活后的目标版本 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description INVALID_ARGUMENT（版本处于 QUEUED/PROCESSING） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    listSessions: {
        parameters: {
            query?: {
                kbId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"][];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreate"];
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description KB_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    listMessages: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePage"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    qaStream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QAStreamRequest"];
            };
        };
        responses: {
            /** @description SSE 事件流 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["QAStreamEvent"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description KB_NOT_FOUND 或 SESSION_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description STREAM_ALREADY_ACTIVE（同一 clientRequestId 已有活跃流，防重复提交） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    qaCancel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QACancelRequest"];
            };
        };
        responses: {
            /** @description 已受理取消，流将以 canceled 事件收尾 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QACancelResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description CANCEL_TARGET_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    debugRetrieval: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DebugRetrievalRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebugRetrievalResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description KB_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    listEvalDatasets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalDataset"][];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    importEvalDataset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    name: string;
                    datasetType: components["schemas"]["DatasetType"];
                };
            };
        };
        responses: {
            /** @description 已导入 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalDataset"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description DUPLICATE_EVAL_DATASET（数据集名称重复） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description INVALID_DATASET_FILE（文件解析失败/必填字段缺失/类别非法） */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    listEvalRuns: {
        parameters: {
            query?: {
                datasetId?: string;
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunPage"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    createEvalRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvalRunCreate"];
            };
        };
        responses: {
            /** @description 已受理 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunAccepted"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description EVAL_DATASET_NOT_FOUND / KB_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    getEvalRun: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunDetail"];
                };
            };
            /** @description EVAL_RUN_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    reviewEvalRunItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvalReviewUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunItem"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description EVAL_RUN_NOT_FOUND（含 run 下无此 item 的情况） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
}
